# Generated by Django 3.2.7 on 2021-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0005_auto_20211004_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='Orders/'),
        ),
    ]
