# Generated by Django 3.2.7 on 2021-10-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
